FROM node:alpine AS build

WORKDIR /app/client

COPY ./package*.json /app/client

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/client/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]