version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backendDev
    image: deannec/pro-invest-re_backend:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontendDev
    image: deannec/pro-invest-re_frontend:latest
    ports:
      - "80:80"
