version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backendDev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontendDev
    ports:
      - "80:80"