FROM node:latest

ENV NODE_ENV=production

ENV ELASTICSEARCH_CREDENTIALS_INDEX=users

ENV ELASTICSEARCH_RENTAL_METRIC_INDEX=rental-metrics

WORKDIR /app/server

COPY ./package*.json /app/server

RUN npm install

COPY . .

EXPOSE 8080

CMD [ "npm", "start" ]

