name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build and push Docker images
        run: |
          docker build -f Dockerfile.backend -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest .
          docker build -f Dockerfile.frontend -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
