name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Node Tests
      working-directory: server
      run: |
        npm install
        npm test

    - name: Run React Tests
      working-directory: client
      run: |
        npm install
        npm test

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Publish Docker Compose
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

    - name: Deploy to Render
      run: |
        curl -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
              -d "accept: application/json" \
              -d "content-type: application/json" \
              https://api.render.com/v1/${{ secrets.FRONTEND_RENDER_SERVICE_ID }}/deploys
        curl -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
              -d "accept: application/json" \
              -d "content-type: application/json" \
              https://api.render.com/v1/${{ secrets.BACKEND_RENDER_SERVICE_ID }}/deploys
